### ISSUE TITLE
User Documentation First Cut

### ISSUE THREAD

**Issue by darrylmelander** [grid-parity-exchange/Prescient#35]
Create documentation targeted at analysts who will use Prescient.

**Comment by jsiirola** [comment]
This task was called out as a priority for the Dispatches project at the monthly update call this week.

**Comment by bknueven** [comment]
TODOs:

- [ ] Verify/update README
- [ ] Decide on documentation platform (Sphinx, Read the Docs, others?)
- [ ] Stand up first cut at user documentation
- [ ] Further refine documentation requirements through issues

**Comment by bknueven** [comment]
Closed by #127 & #133
