### ISSUE TITLE
RTS-GMLC package's Prescient data formatter 

### ISSUE THREAD

**Issue by MajidSKhoshghalb** [grid-parity-exchange/Prescient#61]
Is it possible to use the network topology (gen.csv, bus.csv, branch.csv, etc) provided in [RTS-GMLC package](https://github.com/GridMod/RTS-GMLC) to generate some unit commitment instances for Egret?

**Comment by bknueven** [comment]
Yes, there's a module in Egret to do this directly: https://github.com/grid-parity-exchange/Egret/blob/master/egret/parsers/rts_gmlc_parser.py

Alternatively, you could use `egret.parsers.prescient_dat_parser` to directly load a prescient dat file, no matter how it was generated.

**Comment by MajidSKhoshghalb** [comment]
Thanks!
