### ISSUE TITLE
Add Jupyter to dependencies

### ISSUE THREAD

**Issue by dangunter** [grid-parity-exchange/Prescient#70]
Since the example is a jupyter notebook, you should add Jupyter (i.e. pip package `jupyter`) to the installation dependencies. Otherwise, people installing in some Python or conda env and blindly running "jupyter notebook" might actually run jupyter out of a different environment. I know, I did this!

I also had to install a different version of pywin32, since the version of Jupyter I got by default crashed the kernel. I found the solution here: https://github.com/jupyter/notebook/issues/4980 . Of course this is specific to my setup, but might also be encountered by others.

**Comment by bknueven** [comment]
@dangunter do you have any suggestions for jupyter and/or pywin32 that might get around your initial crashed kernel issue?
